// Generated by CoffeeScript 1.6.3
(function() {
  THREE.Vector3.prototype.summary = function() {
    var d;
    d = 4;
    return "{" + (this.x.toFixed(d)) + ", " + (this.y.toFixed(d)) + ", " + (this.z.toFixed(d)) + "}";
  };

}).call(this);

/*
//@ sourceMappingURL=three-ext.map
*/
